// @generated by wuji-core (specta); 禁止手工编辑。
// 重新生成：WUJI_UPDATE_BINDINGS=1 cargo test -p wuji-core bindings

// This file has been generated by Specta. Do not edit this file manually.
/**  单条 Observation / Segment 的活动状态（09 §6.1）。 */
export type ActivityState = "active" | "idle" | "unknown";

/**  `status_get` / `agent_get_status` 的返回（09 §8.4）。 */
export type AgentStatusDto = {
	agentVersion: string,
	protocolVersion: number,
	schemaVersion: number,
	processState: ProcessState,
	captureState: CaptureState,
	writerState: WriterState,
	runtimeId: RuntimeId,
	heartbeatAtUtcMs: Int64String | null,
	lastObservationAtUtcMs: Int64String | null,
	lastWriteAtUtcMs: Int64String | null,
	captureQueueDepth: number,
	writerQueueDepth: number,
	droppedCaptureCount: Int64String,
	droppedWriterCount: Int64String,
	safeErrorCode: SafeErrorCode | null,
};

export type AppDto = {
	appId: Int64String,
	displayName: string,
};

/**  采集状态（schema `agent_runtime.capture_state`）。 */
export type CaptureState = "stopped" | "running" | "paused";

/**  字段级安全错误（09 §8.2 `fieldErrors`；message 为中文安全提示）。 */
export type FieldError = {
	field: string,
	message: string,
};

/**  数据缺口类型（schema `capture_gaps.kind`）。 */
export type GapKind = "sampling_transition" | "capture_delayed" | "privacy_excluded" | "capture_queue_drop" | "writer_queue_drop" | "capture_paused" | "capture_stopped" | "system_sleep" | "session_locked" | "agent_restart" | "clock_changed" | "capture_error";

/**  Heatmap 单格（09 §8.4）：稀疏返回，强度等级由 Rust 归一化，前端不得重推。 */
export type HeatmapCellDto = {
	localDate: string,
	localHour: number,
	activeDurationMs: Int64String,
	idleDurationMs: Int64String,
	unknownDurationMs: Int64String,
	intensityLevel: number,
};

/**
 *  Heatmap 响应：以 `range_end_local_date` 为范围终点的最近 days 天 × 24 小时。
 *  `today` 始终是查询时 DB reporting 时区下的真实今天，不随历史范围改变；
 *  cells 只含时长 > 0 的格子（09 §8.4）。
 */
export type HeatmapDto = {
	today: LocalDate,
	rangeEndLocalDate: LocalDate,
	reportingTimeZoneId: string,
	days: number,
	cells: HeatmapCellDto[],
};

/**  i64 的十进制字符串表示（branded；serde 只接受字符串，避免 JS number 精度问题）。 */
export type Int64String = string & { readonly __brand: "Int64String" };

/**  严格 `YYYY-MM-DD` 本地日期（09 §8.4）。 */
export type LocalDate = string;

/**  Agent 进程状态（schema `agent_runtime.process_state`）。 */
export type ProcessState = "starting" | "running" | "degraded" | "faulted" | "shutting_down" | "stopped";

/**  open/closed 行状态（schema 各 `status` 列）。 */
export type RowStatus = "open" | "closed";

/**  ULID 运行实例标识（26 字符；schema `agent_runtime.runtime_id`）。 */
export type RuntimeId = string;

/**  IPC/Tauri 边界上的安全错误结构（09 §8.2 envelope 的 `error` 字段）。 */
export type SafeError = {
	code: SafeErrorCode,
	/**  面向用户的中文安全说明；不得包含原始异常、路径、SQL、SID 或标题。 */
	message: string,
};

/**  09 §8.2 冻结的稳定错误码。 */
export type SafeErrorCode = "IPC_PROTOCOL_UNSUPPORTED" | "IPC_CHANNEL_MISMATCH" | "IPC_INVALID_MESSAGE" | "IPC_PAYLOAD_TOO_LARGE" | "IPC_REQUEST_ID_REUSED" | "INVALID_ARGUMENT" | "CAPTURE_INVALID_STATE" | "AGENT_WRITER_DEGRADED" | "AGENT_WRITER_FAULTED" | "DB_UNAVAILABLE" | "DB_SCHEMA_UNSUPPORTED" | "TIME_ZONE_UNAVAILABLE" | "SETTINGS_CONFLICT" | "SETTINGS_INVALID" | "SETTINGS_SAVED_NOT_APPLIED" | "STARTUP_REGISTRY_FAILED" | "STARTUP_RECONCILIATION_REQUIRED" | "VERSION_INCOMPATIBLE" | "INTERNAL_SAFE_ERROR";

/**
 *  Settings JSON 完整字段集（09 §9：只允许这五个业务字段加 schemaVersion/revision）。
 *  Desktop 本地偏好（如自动拉起 Agent）不在此集合，见 09 §9.4。
 */
export type Settings = {
	schemaVersion: number,
	/**  十进制字符串（09 §9：revision 是 string，不是 number）。 */
	revision: string,
	samplingIntervalSeconds: number,
	idleThresholdSeconds: number,
	workBreakIdleSeconds: number,
	excludedProcessNames: string[],
	startCaptureOnLogin: boolean,
};

/**  Settings 面向 React 的表示（09 §8.4）：保存与已应用分开显示。 */
export type SettingsDto = {
	schemaVersion: number,
	revision: string,
	persisted: boolean,
	appliedRevision: string,
	samplingIntervalSeconds: number,
	idleThresholdSeconds: number,
	workBreakIdleSeconds: number,
	excludedProcessNames: string[],
	startCaptureOnLogin: boolean,
};

export type TimelineGapDto = {
	gapId: Int64String,
	gapKind: GapKind,
	startAtUtcMs: Int64String,
	endAtUtcMs: Int64String | null,
	status: RowStatus,
	eventCount: number,
};

/**  Timeline 分页项（`kind` 判别；09 §8.4）。 */
export type TimelineItem = {
	kind: "segment",
} & TimelineSegmentDto | {
	kind: "gap",
} & TimelineGapDto;

export type TimelinePageDto = {
	localDate: LocalDate,
	reportingTimeZoneId: string,
	items: TimelineItem[],
	nextCursor: string | null,
};

export type TimelineSegmentDto = {
	segmentId: Int64String,
	app: AppDto,
	activityState: ActivityState,
	startAtUtcMs: Int64String,
	endAtUtcMs: Int64String,
	durationMs: Int64String,
	status: RowStatus,
};

export type TodayDto = {
	localDate: LocalDate,
	reportingTimeZoneId: string,
	activeDurationMs: Int64String,
	currentApp: AppDto | null,
	lastApp: AppDto | null,
	longestWorkBlockActiveMs: Int64String,
	workBlockCount: Int64String,
	rawAppSwitchCount: Int64String,
	topApps: TopAppDto[],
	quality: TodayQualityDto,
};

export type TodayQualityDto = {
	/**  该 local date 无非 sampling_transition gap 且 droppedCount 为 0（09 §8.4 字段口径）。 */
	isComplete: boolean,
	gapCount: Int64String,
	droppedCount: Int64String,
};

export type TopAppDto = {
	app: AppDto,
	activeDurationMs: Int64String,
};

/**  Writer 状态（schema `agent_runtime.writer_state`）。 */
export type WriterState = "healthy" | "degraded" | "faulted";
