<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QuantifiedSelf.Windows.Application\QuantifiedSelf.Windows.Application.csproj" />
    <ProjectReference Include="..\QuantifiedSelf.Windows.Core\QuantifiedSelf.Windows.Core.csproj" />
    <ProjectReference Include="..\QuantifiedSelf.Windows.Infrastructure\QuantifiedSelf.Windows.Infrastructure.csproj" />
    <ProjectReference Include="..\QuantifiedSelf.Windows.Agent\QuantifiedSelf.Windows.Agent.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QuantifiedSelf.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="*" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="*" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyTitle>WUJI</AssemblyTitle>
    <Product>WUJI</Product>
    <Company>WUJI</Company>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <AssemblyDescription>WUJI Windows App</AssemblyDescription>
    <Description>WUJI Windows App</Description>
  </PropertyGroup>

</Project>
