//! Rust DTO → TypeScript 声明生成（09 §8.4）。
//!
//! serde 类型是唯一来源；生成文件 `bindings/wuji-core.ts` 进入源码管理，
//! drift 测试失败即表示 DTO 变更后未重新生成（CI 自动门禁）。

use specta::Types;
use specta_typescript::Typescript;

use crate::dto::{
    AgentStatusDto, AppDto, SettingsDto, TimelinePageDto, TodayDto, TodayQualityDto, TopAppDto,
};
use crate::error::{SafeError, SafeErrorCode};
use crate::settings::{FieldError, Settings};

/// 生成文件相对 crate 根的位置。
pub const BINDINGS_FILE_NAME: &str = "bindings/wuji-core.ts";
/// Desktop 侧的同一文件（双副本必须逐字节一致；更新流程同时写两处）。
pub const DESKTOP_BINDINGS_FILE_NAME: &str = "../../apps/desktop/src/types/wuji-core.ts";

const HEADER: &str = "// @generated by wuji-core (specta); 禁止手工编辑。\n\
                      // 重新生成：WUJI_UPDATE_BINDINGS=1 cargo test -p wuji-core bindings\n";

/// specta 对 `Int64String`（`String` 新类型）的原始输出别名。
const INT64_ALIAS: &str = "export type Int64String = string;";
/// 品牌化别名（09 §8.4、审核 R07）：防止把任意 string 当作 i64 文本误用。
const INT64_BRANDED: &str =
    "export type Int64String = string & { readonly __brand: \"Int64String\" };";

/// 注册全部跨边界类型。
pub fn type_collection() -> Types {
    Types::default()
        .register::<AppDto>()
        .register::<AgentStatusDto>()
        .register::<TodayDto>()
        .register::<TopAppDto>()
        .register::<TodayQualityDto>()
        .register::<TimelinePageDto>()
        .register::<SettingsDto>()
        .register::<Settings>()
        .register::<FieldError>()
        .register::<SafeError>()
        .register::<SafeErrorCode>()
}

/// 生成 TypeScript 声明文本（含 Int64String 品牌替换；specta 输出漂移时替换失败即报错）。
pub fn export_typescript() -> Result<String, String> {
    let exported = Typescript::default()
        .header(HEADER)
        .export(&type_collection(), specta_serde::Format)
        .map_err(|e| e.to_string())?;
    if !exported.contains(INT64_ALIAS) {
        return Err("specta 输出缺少 Int64String 别名，品牌替换无法应用".to_string());
    }
    Ok(exported.replacen(INT64_ALIAS, INT64_BRANDED, 1))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// drift 门禁：生成内容必须与两处入库文件逐字节一致（crate bindings 与 desktop 副本）。
    /// 更新方式：WUJI_UPDATE_BINDINGS=1 cargo test -p wuji-core bindings
    #[test]
    fn bindings_have_no_drift() {
        let generated = export_typescript().expect("TypeScript 生成失败");
        let crate_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
        let path = crate_root.join(BINDINGS_FILE_NAME);
        let desktop_path = crate_root.join(DESKTOP_BINDINGS_FILE_NAME);

        if std::env::var_os("WUJI_UPDATE_BINDINGS").is_some() {
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, &generated).unwrap();
            std::fs::write(&desktop_path, &generated).unwrap();
            return;
        }

        let committed = std::fs::read_to_string(&path).unwrap_or_else(|_| {
            panic!("缺少 {BINDINGS_FILE_NAME}；请先以 WUJI_UPDATE_BINDINGS=1 生成")
        });
        assert_eq!(
            generated, committed,
            "DTO 与 TypeScript 声明存在 drift；请以 WUJI_UPDATE_BINDINGS=1 重新生成"
        );
        let desktop = std::fs::read_to_string(&desktop_path).unwrap_or_else(|_| {
            panic!("缺少 {DESKTOP_BINDINGS_FILE_NAME}；请以 WUJI_UPDATE_BINDINGS=1 重新生成")
        });
        assert_eq!(
            generated, desktop,
            "crate bindings 与 desktop 副本不一致；请以 WUJI_UPDATE_BINDINGS=1 重新生成"
        );
    }

    #[test]
    fn int64_fields_export_as_branded_string() {
        let generated = export_typescript().expect("TypeScript 生成失败");
        assert!(
            generated.contains(INT64_BRANDED),
            "i64 必须导出为 branded string（09 §8.4、审核 R07）：\n{generated}"
        );
        assert!(
            !generated.contains(INT64_ALIAS),
            "原始 string 别名必须被品牌替换：\n{generated}"
        );
        assert!(
            generated.contains("activeDurationMs: Int64String"),
            "i64 字段必须引用 branded 类型：\n{generated}"
        );
    }
}
