<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\QuantifiedSelf.Windows.Application\QuantifiedSelf.Windows.Application.csproj" />
    <ProjectReference Include="..\QuantifiedSelf.Windows.Core\QuantifiedSelf.Windows.Core.csproj" />
    <ProjectReference Include="..\QuantifiedSelf.Windows.Infrastructure\QuantifiedSelf.Windows.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
